apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/elasticsearch-data/

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  elasticsearch-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: elasticsearch-data
  resources:
    requests:
      storage: 1Gi