apiVersion: v1
kind: Service
metadata:
  labels:
    app: elassandra
  name: elassandra
  namespace: database
spec:
  clusterIP: None
  ports:
    - name: cassandra
      port: 9042
    - name: http
      port: 9200
    - name: transport
      port: 9300
  selector:
    app: elassandra

---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: elassandra
  namespace: database
spec:
  serviceName: elassandra
  replicas: 2
  template:
    metadata:
      namespace: elassandra
      labels:
        app: elassandra
    spec:
      volumes:
        - name: elassandra-data
          persistentVolumeClaim:
            claimName: elassandra-data-pvc
      containers:
      - name: elassandra
        image: strapdata/elassandra:6.2.3.18
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 300m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        env:
        - name: CASSANDRA_SEEDS
          value: elassandra-0.elassandra.elassandra.svc.cluster.local
        - name: MAX_HEAP_SIZE
          value: 256M
        - name: HEAP_NEWSIZE
          value: 100M
        - name: CASSANDRA_CLUSTER_NAME
          value: "Cassandra"
        - name: CASSANDRA_DC
          value: "DC1"
        - name: CASSANDRA_RACK
          value: "Rack1"
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: GossipingPropertyFileSnitch
        volumeMounts:
        - name: elassandra-data
          mountPath: /var/lib/cassandra/data
