apiVersion: v1
kind: PersistentVolume
metadata:
  name: elassandra-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/elassandra-data/

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  elassandra-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: elassandra-data
  resources:
    requests:
      storage: 1Gi